# Generated by Django 4.2.14 on 2024-07-26 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-images/')),
                ('is_cover', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.baseproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('pi', 'جفت'), ('na', 'عددی')], max_length=2)),
                ('price', models.IntegerField()),
                ('price_after_discount', models.IntegerField()),
                ('discount_percent', models.PositiveIntegerField()),
                ('start_discount', models.DateTimeField()),
                ('end_discount', models.DateTimeField()),
                ('length_package', models.IntegerField(blank=True, null=True)),
                ('width_package', models.IntegerField(blank=True, null=True)),
                ('height_package', models.IntegerField(blank=True, null=True)),
                ('weight_package', models.IntegerField(blank=True, null=True)),
                ('shenase_kala', models.CharField(max_length=14, null=True)),
                ('barcode', models.CharField(max_length=16, null=True)),
                ('base_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.baseproduct')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.color')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.size')),
            ],
        ),
    ]
