# Generated by Django 4.2.14 on 2024-07-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
