# Generated by Django 4.2.14 on 2024-07-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_orderdate_ordertime_order_date_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='purchased_price',
        ),
    ]
