# Generated by Django 4.2.14 on 2024-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_baseproduct_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(choices=[('c', 'تایید'), ('w', 'در انتظار تایید'), ('n', 'عدم تایید')], default='w', max_length=1),
        ),
    ]
