# Generated by Django 4.2.14 on 2024-07-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
