# Generated by Django 4.2.14 on 2024-07-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SetProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='store.baseproduct')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productproperties')),
            ],
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='properties',
            field=models.ManyToManyField(related_name='categories', to='store.productproperties'),
        ),
    ]
