# Generated by Django 4.2.14 on 2024-07-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productproperties_setproductproperty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='code_of_color',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
