# Generated by Django 4.2.14 on 2024-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_status_order_order_status_order_status_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('co', 'جاری'), ('d', 'تحویل شده'), ('r', 'مرجوعی'), ('c', 'لغو شده')], default='co', max_length=2),
        ),
    ]
