# Generated by Django 4.2.14 on 2024-07-29 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPhotography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=11)),
                ('mahalle', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('store_name', models.CharField(max_length=255)),
                ('request_text', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_photography', to='store.city')),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_photography', to='store.neighbourhood')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_photography', to='store.province')),
            ],
        ),
    ]
