# Generated by Django 4.2.14 on 2024-07-30 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_requestphotography'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.store'),
        ),
    ]
