# Generated by Django 4.2.14 on 2024-08-01 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.producttype'),
        ),
    ]
