# Generated by Django 4.2.14 on 2024-08-01 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_baseproduct_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_discount',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='start_discount',
            field=models.DateTimeField(null=True),
        ),
    ]
