# Generated by Django 4.2.14 on 2024-08-01 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sameproduct',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='same_products', to='store.store'),
        ),
    ]
