# Generated by Django 4.2.14 on 2024-08-09 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_sameproduct_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
