# Generated by Django 4.2.14 on 2024-08-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_datetime_created_product_datetime_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productanswercomment',
            options={'ordering': ('-datetime_created',)},
        ),
        migrations.AlterModelOptions(
            name='productcomment',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
