# Generated by Django 4.2.14 on 2024-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_coupondiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
