# Generated by Django 4.2.14 on 2024-08-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_order_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.BooleanField(default=False),
        ),
    ]
