# Generated by Django 4.2.14 on 2024-08-12 22:13

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_cart_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.IntegerField(default=store.models.generate_tracking_code_order),
        ),
    ]
