# Generated by Django 4.2.14 on 2024-08-15 17:03

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_order_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_code',
            field=models.CharField(default=store.models.random_code_base_product, max_length=10),
        ),
    ]
