# Generated by Django 4.2.14 on 2024-08-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_baseproduct_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseproduct',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
