# Generated by Django 4.2.14 on 2024-08-17 00:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_baseproduct_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'ordering': ('datetime_created',)},
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseproduct',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
