# Generated by Django 4.2.14 on 2024-08-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_baseproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseproduct',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
