# Generated by Django 4.2.14 on 2024-08-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_baseproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseproduct',
            name='product_authenticity',
            field=models.CharField(choices=[('o', 'اصل ، اوریجینال'), ('hc', 'های کپی'), ('c', 'کپی')], max_length=2),
        ),
    ]
