# Generated by Django 4.2.14 on 2024-07-25 15:32

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(max_length=11, unique=True, validators=[core.validators.validate_isdigit]),
        ),
    ]
