# Generated by Django 4.2.3 on 2024-07-25 17:04

import core.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=11)),
                ('otp_code', models.CharField(max_length=5)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('valid_until', models.DateTimeField(default=core.models.get_datetime_now, null=True)),
            ],
        ),
    ]
