# Generated by Django 4.2.14 on 2024-08-21 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_baseproduct_options'),
        ('panel', '0002_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ShipingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.province')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='store.province')),
                ('sending_method', models.ManyToManyField(related_name='costs', to='panel.sendingmethod')),
                ('shiping_range', models.ManyToManyField(related_name='costs', to='panel.shipingrange')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='store.store')),
            ],
        ),
    ]
