# Generated by Django 4.2.14 on 2024-08-21 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_baseproduct_options'),
        ('panel', '0003_sendingmethod_shipingrange_shipingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendingmethod',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='store.store'),
        ),
        migrations.AddField(
            model_name='shipingrange',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='store.store'),
        ),
    ]
