# Generated by Django 4.2.14 on 2024-08-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_sendingmethod_store_shipingrange_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipingcost',
            name='shiping_range',
        ),
        migrations.RemoveField(
            model_name='shipingcost',
            name='sending_method',
        ),
        migrations.AddField(
            model_name='shipingcost',
            name='sending_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sending_methods', to='panel.sendingmethod'),
        ),
    ]
