# Generated by Django 4.2.14 on 2024-08-21 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_baseproduct_product_authenticity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0005_remove_shipingcost_shiping_range_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('a', 'تایید شده'), ('w', 'در انتظار تایید'), ('n', 'عدم تایید')], max_length=1)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_add_product', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_add_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
