# Generated by Django 4.2.14 on 2024-08-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_requestaddproduct_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestaddproduct',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
