# Generated by Django 4.2.14 on 2024-08-22 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_favoriteproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteProduct',
        ),
    ]
